# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  name: Azure Pipelines
  
steps:
  - task: NuGetCommand@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: '6bd0cedb-2346-43ac-9ae3-9a2dec1a9044'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csprojs;!**/*Benchmarks.csproj;!**/*Simulator.csproj;!**/*UI*.csproj'
  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csprojs;!**/*Benchmarks.csproj;!**/*Simulator.csproj;!**/*UI*.csproj'
      versioningScheme: 'byBuildNumber'
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '6bd0cedb-2346-43ac-9ae3-9a2dec1a9044'
      allowPackageConflicts: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ProcessSimulator'
      publishLocation: 'Container'